### ISSUE TITLE
Add Darwin Build support

### ISSUE THREAD

**Issue by Slime90** [dwarfmaster/arkenfox-nixos#22]
Hello,

I am trying to integrate your project into my personal config flake, and it works as expected on x86 linux. However when I attempt to build on my x86_64-darwin machine, I get the error:

`error: a 'x86_64-linux' with features {} is required to build '/nix/store/fdyjg3gkpw67vbbw5337bzm3a13kw520-arkenfox-extractor.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}
(use '--show-trace' to show detailed location information)`

Darwin support in the future would be greatly appreciated!

**Comment by dwarfmaster** [comment]
Right, due to laziness on my part I hardcoded the architecture to the one I was using. However as long as you use only the overlays and modules it should work. Can you detail a bit more what you're doing ?

**Comment by dwarfmaster** [comment]
I though it would work if used like that, I'll have a look when I have the time.

**Comment by Slime90** [comment]
Opened #23 to address this for your review, likely needs some additional work.

**Comment by dwarfmaster** [comment]
Usage of the module on darwin should be fixed now. I still plan to use flake utils but there are a few more things I want to refactor before.

**Comment by Slime90** [comment]
Thanks so much for the update, I see that you ultimately did implement flake-utils and a bunch of other nice stuff this morning. Quick aside, can you `++` the `powerpc64le-linux` system to eachDeafultSystem? I have such a system that I will be experimenting soon on with nixos.

**Comment by dwarfmaster** [comment]
As long as you only use the module and/or overlay, it should work for every system. Adding a non default system as output would be complicated since pre-commit-hook.nix wouldn't support it.

**Comment by dwarfmaster** [comment]
Is it working on darwin ? If yes could you close the issue ?

**Comment by dwarfmaster** [comment]
Closing, feel free to reopen if it still isn't working.
