### ISSUE TITLE
Need help, NixOS-config doesn't build

### ISSUE THREAD

**Issue by theRoboxx** [dwarfmaster/arkenfox-nixos#42]
Hi, I'm new to nix and NixOS and would like to use this firefox option to add the user.js automatically.
Unfortunately, I think I missed something from your documentation because there is an error while building the config.

I  added this part to my config and don't know what else I should do to fix the problem:

```
# firefox.nix 
{ pkgs, inputs,  ... }:
{
  programs.firefox = {
    enable = true;
    arkenfox = {
      enable = true;
      version = "119.0";
    };

    profiles.testing = {
    
      arkenfox = {
        enable = true;
      };
    };
  };
}
```
And this is the error:

```
error: The option `home-manager.users.tom.programs.firefox.arkenfox' does not exist. Definition values:
       - In `/home/tom/.dotfiles/nixos-config/firefox.nix':
           {
             enable = true;
             version = "119.0";
           }
```
How do I enable this option for home-manager?

**Comment by theRoboxx** [comment]
Nethermind I'm blind, this answer was posted here: https://github.com/dwarfmaster/arkenfox-nixos/issues/38#issuecomment-1744435365

@dwarfmaster Could you please add this to the README.md?

**Comment by storopoli** [comment]
@theRoboxx check my arkenfox configs here: https://github.com/storopoli/flakes/blob/8f2be991a0a2b56d6bb4410aa5a985e69535cc29/home-manager/linux/firefox.nix#L37-L46

**Comment by theRoboxx** [comment]
https://github.com/storopoli/flakes/blob/8f2be991a0a2b56d6bb4410aa5a985e69535cc29/flake.nix#L104

This line fixed the import error. Thank you very much :smiley:

**Comment by dwarfmaster** [comment]
I did not include in the documentation how to import the home-manager module because I assumed it actually depends on how precisely your configuration is setup, and is not specific to arkenfox-nixos. However, you are at least the third person I am aware of that had a problem with this step, so I'll try to add something to the documentation when I have the time.
