### ISSUE TITLE
overrides approach

### ISSUE THREAD

**Issue by iambeingtracked** [dwarfmaster/arkenfox-nixos#51]
Is it possible to use arkenfox-nixos as the regular arkenfox user.js, enabling everything by default and only disabling specific prefs?

**Comment by dwarfmaster** [comment]
Not really, you need to enable each section explicitely, and even then, the settings that are commented in the user.js will still be disabled by default (however that might be what you want ?).

I should be possible to create a new option enable all sections at once. I will look into it when I have to motivation to do so.

**Comment by iambeingtracked** [comment]
Thank you. That option really helps with migrating an existing arkenfox setup from a non-nix machine as the way arkenfox is intended to be used is to enable it all and then override what you want
