### ISSUE TITLE
Module does not work (Option not found)

### ISSUE THREAD

**Issue by Layer-09** [dwarfmaster/arkenfox-nixos#52]
The example provided by the repo does not work correctly. Any attempt to build is met with: 
`home-manager.users.user1.programs.firefox.profiles.Default.arkenfox."0001"' does not exist`

The module is imported. This happens with any number. If `arkenfox.enable` is set to `false`, the build completes, but it does not retain any options set in `profiles.Default.arkenfox`.

**Comment by d-brasher** [comment]
I think that is expected, since the option `0001` doesn't exist.

You can browse the available options and sections [here](https://github.com/arkenfox/user.js/blob/master/user.js).
After section `0000` there is `0100` with the first option being `0102`.

**Comment by Layer-09** [comment]
It's the same exact response on any option I input, valid or not. I'd expect the configuration below to work, yet for some reason it doesn't.
```nix
arkenfox = {
  enable = true;
  version = "master";
};

profiles.Default.arkenfox = {
  enable = true;
      
  "0105".enable = true; 
}; 
```
```bash
The option `home-manager.users.user1.programs.firefox.profiles.Default.arkenfox."0105"' does not exist.
```

@d-brasher

**Comment by Layer-09** [comment]
This here was the issue `"0100"."0105".enable = true; `.
