### ISSUE TITLE
Arkenfox v128.0

### ISSUE THREAD

**Issue by OliverGeneser** [dwarfmaster/arkenfox-nixos#53]
Hey @dwarfmaster

Thanks for your amazing work!

Can you run the regenerate action manually, so we don't have to wait until Sunday to get the newest 128.0 update?

**Comment by dwarfmaster** [comment]
I just saw your message, it is merged now even if a bit late. Maybe I should find a way to make it easy for users to run the regenerate action locally through nix, because I tend to be a bit slow the react to github issues.
